spring:
  application:
    name: api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.223.242:3306/videodb?tinyInt1isBit=false&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: mysqlpassWord@666.
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 47.113.223.242
    database: 0
    password: myredispassWord@666.
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 30MB
  rabbitmq:
    host: 47.113.223.242
    port: 5672
    username: root
    password: rabbitmqPassWord@666.
server:
  port: 7529
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  spring.servlet.multipart.maxFileSize=1MB
#  spring.servlet.multipart.maxRequestSize=1MB
# 文件相关参数
file:
  path: /src/main/resources/static/uploads
  # 20 * 1024 * 1024
  chunk-size: 20971520

rabbit:
   ttl: 6000
